### ISSUE TITLE
Error with rules containing aggregates with symbolic sets of different tuple sizes

### ISSUE THREAD

**Issue by 0xbb** [hexhex/core#18]
Hi,
I am getting an error when using multiple aggregates within one rule when the tuples of the symbolic sets have different sizes. 
To me this seems like a bug in dlvhex and therefore I wanted to report you this error.

Example:
```
a(1,1). a(2,1).
c(A,B) :- A = #count{X,Y : a(X,Y)},  B = #count{Y : a(X,Y)}.
```
Output:
```GeneralError: Symbolic set of aggregate "B = #count { Y : a(X,Y) }" contains tuples of varying sizes```

Expected Output:
```{a(1,1),a(2,1),c(2,1)}```

Greetings, 
Bruno

**Comment by credl** [comment]
Thank you. The bug is fixed.

**Comment by 0xbb** [comment]
Thank you for your incredible fast bug fix! :)
It works now.
