### ISSUE TITLE
dlvhex benchmarking. Getting number of rules and atoms used?

### ISSUE THREAD

**Issue by faseehahmad** [hexhex/core#34]
Hello Everyone,

I am currently using dlvhex for my project. I want to find the number of rules and atoms for solving a particular problem instance. I tried using --verbose levels but they did not work. I also tried --enable-benchmark command from the manual along with --dumpstats command. But, it gives the following error.

UsageError: Fatal: Unknown option(s): --enable-benchmarks

Am I doing something wrong?
Thanks

**Comment by peschue** [comment]
Hello Ahmad,

Did you use --enable-benchmarks during the configuration? This option should be used when you do `./configure` for the package before building with `make`.

You can try the option `--verbose=255` to get all possible output from dlvhex, or `--verbose=8` should give you just the statistics output of benchmarking.

I think the number of rules and atoms is part of that output (if you configure with --enable-benchmarks).

Best,
Peter

**Comment by faseehahmad** [comment]
I reconfigured it using --enable-benchmark, but still there it gives the same error. dlvhex command line help has no option of --enable-benchmark

**Comment by peschue** [comment]
After reconfiguring you need to rebuild everything by running `make clean` and then `make`.

Afterwards you run **dlvhex** with `dlvhex2 --verbose=255` to get debug and benchmarking output or with `dlvhex2 --verbose=8` to get only benchmarking output.

**Comment by faseehahmad** [comment]
Now it works. Thank you so much

**Comment by peschue** [comment]
You are welcome. I will close the issue. If you encounter further problems please feel free to reopen the issue.
